project:
  type: website
  output-dir: docs

website:
  title: "Leo Micollet"
  favicon: img/lost_BMOXL.png
  navbar:
    left:
      - href: index.qmd
        #text: Home
      - research.qmd
    right:
      - about.qmd
  page-footer:
    background: light
    center: Copyright 2024, Leo Micollet

format:
  html:
    theme: styles.scss
    css: styles.css
    toc: true
