project:
  type: website
  output-dir: docs
  
website:
  title: "Leo Micollet"
  navbar:
    left:
      - href: index.qmd
        #text: Home
      - about.qmd
    right:
      - research.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true
